import numpy as np
import matplotlib.pyplot as plt

N = 32
n = np.arange(N)

bart = np.bartlett(N)
black = np.blackman(N)
ham = np.hamming(N)
han = np.hanning(N)
kai = np.kaiser(N, 2)
rect = np.ones(N)

plt.subplot(4, 3, 2)
plt.plot(bart)
plt.plot(black)
plt.plot(ham)
plt.plot(han)
plt.plot(kai)
plt.plot(rect)
plt.title("Wykresy okien")
plt.ylabel("Waga")
plt.xlabel("Numer próbki")
plt.legend(['bartlett', 'blackman', 'hamming', 'hanning', 'kaiser', 'prostokątne'])

y = np.sin(2 * np.pi * 2.5 * n / N)

plt.subplot(4, 3, 1)
plt.plot(n, y)
plt.title("y")
plt.ylabel("Amplituda")
plt.xlabel("Numer próbki")

Y = np.abs(np.fft.fft(y) * 2 / N)
y1 = y.copy()

bartY = np.abs(np.fft.fft(y1 * bart) * 2 / N)
blackY = np.abs(np.fft.fft(y1 * black) * 2 / N)
hamY = np.abs(np.fft.fft(y1 * ham) * 2 / N)
hanY = np.abs(np.fft.fft(y1 * han) * 2 / N)
kaiY = np.abs(np.fft.fft(y1 * kai) * 2 / N)
rectY = np.abs(np.fft.fft(y1 * rect) * 2 / N)

plt.subplot(4, 3, 4)
plt.stem(n, Y)
plt.title("Moduł FFT - Brak okna")
plt.ylabel("Magnituda")
plt.xlabel("Numer pasma częstotliwościowego")
plt.subplot(4, 3, 5)
plt.stem(n, bartY)
plt.title("Moduł FFT - Bartlett")
plt.ylabel("Magnituda")
plt.xlabel("Numer pasma częstotliwościowego")
plt.subplot(4, 3, 6)
plt.stem(n, blackY)
plt.title("Moduł FFT - Blackman")
plt.ylabel("Magnituda")
plt.xlabel("Numer pasma częstotliwościowego")
plt.subplot(4, 3, 7)
plt.stem(n, hamY)
plt.title("Moduł FFT - Hamming")
plt.ylabel("Magnituda")
plt.xlabel("Numer pasma częstotliwościowego")
plt.subplot(4, 3, 8)
plt.stem(n, hanY)
plt.title("Moduł FFT - Hanning")
plt.ylabel("Magnituda")
plt.xlabel("Numer pasma częstotliwościowego")
plt.subplot(4, 3, 9)
plt.stem(n, kaiY)
plt.title("Moduł FFT - Kaiser")
plt.ylabel("Magnituda")
plt.xlabel("Numer pasma częstotliwościowego")
plt.subplot(4, 3, 10)
plt.stem(rectY)
plt.title("Moduł FFT - Rectwin")
plt.ylabel("Magnituda")
plt.xlabel("Numer pasma częstotliwościowego")

plt.tight_layout()
plt.show()